# Generated by Django 4.1.3 on 2022-11-15 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_livro'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='ISBN',
            field=models.CharField(default=0, max_length=32),
        ),
        migrations.AddField(
            model_name='livro',
            name='titulo',
            field=models.CharField(default=' ', max_length=255),
        ),
    ]
